name: billyb
favicon: null
layout_spectrum: 0.45871823630295694
typography_spectrum: 0.7817920790985227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050503'
    - '#365128'
    - '#4d7540'
    - '#92d94e'
    - '#6b9754'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
