name: billyb
favicon: null
layout_spectrum: 0.2577
typography_spectrum: 0.7817920790985227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#b4afab'
    - '#d6dde7'
    - '#557792'
    - '#0d5ead'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
