name: billyb
favicon: null
layout_spectrum: 0.74669
typography_spectrum: 0.7817920790985227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050503'
    - '#365128'
    - '#4d7540'
    - '#92d94e'
    - '#6b9754'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
